//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.FoxTTS.localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACT.FoxTTS.localization.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ACT TTS插件 的本地化字符串。
        /// </summary>
        internal static string actPanelTitle {
            get {
                return ResourceManager.GetString("actPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查更新 的本地化字符串。
        /// </summary>
        internal static string buttonCheckUpdate {
            get {
                return ResourceManager.GetString("buttonCheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开下载页面 的本地化字符串。
        /// </summary>
        internal static string buttonDownloadUpdate {
            get {
                return ResourceManager.GetString("buttonDownloadUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 忽略错误（插件将无法正常工作） 的本地化字符串。
        /// </summary>
        internal static string buttonIgnore {
            get {
                return ResourceManager.GetString("buttonIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 忽略 的本地化字符串。
        /// </summary>
        internal static string buttonIgnoreVersion {
            get {
                return ResourceManager.GetString("buttonIgnoreVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 听听看! 的本地化字符串。
        /// </summary>
        internal static string buttonPreview {
            get {
                return ResourceManager.GetString("buttonPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置为默认设置 的本地化字符串。
        /// </summary>
        internal static string buttonResetToDefault {
            get {
                return ResourceManager.GetString("buttonResetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载上一次的设置 的本地化字符串。
        /// </summary>
        internal static string buttonRestoreFromBackup {
            get {
                return ResourceManager.GetString("buttonRestoreFromBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 稍后 的本地化字符串。
        /// </summary>
        internal static string buttonUpdateLater {
            get {
                return ResourceManager.GetString("buttonUpdateLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        internal static string buttonUpdateNow {
            get {
                return ResourceManager.GetString("buttonUpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动检查更新 的本地化字符串。
        /// </summary>
        internal static string checkBoxCheckUpdate {
            get {
                return ResourceManager.GetString("checkBoxCheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出时清空 TTS 缓存 的本地化字符串。
        /// </summary>
        internal static string checkBoxClearCacheExit {
            get {
                return ResourceManager.GetString("checkBoxClearCacheExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只提示稳定版更新 的本地化字符串。
        /// </summary>
        internal static string checkBoxNotifyStableOnly {
            get {
                return ResourceManager.GetString("checkBoxNotifyStableOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件集成 的本地化字符串。
        /// </summary>
        internal static string groupBoxIntegration {
            get {
                return ResourceManager.GetString("groupBoxIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回放设置 的本地化字符串。
        /// </summary>
        internal static string groupBoxPlayback {
            get {
                return ResourceManager.GetString("groupBoxPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 声音预览 的本地化字符串。
        /// </summary>
        internal static string groupBoxPreview {
            get {
                return ResourceManager.GetString("groupBoxPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TTS 引擎 的本地化字符串。
        /// </summary>
        internal static string groupBoxTTSEngine {
            get {
                return ResourceManager.GetString("groupBoxTTSEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引擎详情 的本地化字符串。
        /// </summary>
        internal static string groupBoxTTSEngineDetail {
            get {
                return ResourceManager.GetString("groupBoxTTSEngineDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件更新 的本地化字符串。
        /// </summary>
        internal static string groupBoxUpdate {
            get {
                return ResourceManager.GetString("groupBoxUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 API Key: 的本地化字符串。
        /// </summary>
        internal static string labelApiKey {
            get {
                return ResourceManager.GetString("labelApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前版本: 的本地化字符串。
        /// </summary>
        internal static string labelCurrentVersion {
            get {
                return ResourceManager.GetString("labelCurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最新稳定版本: 的本地化字符串。
        /// </summary>
        internal static string labelLatestStableVersion {
            get {
                return ResourceManager.GetString("labelLatestStableVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最新版本: 的本地化字符串。
        /// </summary>
        internal static string labelLatestVersion {
            get {
                return ResourceManager.GetString("labelLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言: 的本地化字符串。
        /// </summary>
        internal static string labelMainLanguage {
            get {
                return ResourceManager.GetString("labelMainLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主音量: 的本地化字符串。
        /// </summary>
        internal static string labelMasterVolume {
            get {
                return ResourceManager.GetString("labelMasterVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 *需要重启ACT。 的本地化字符串。
        /// </summary>
        internal static string labelNeedToRestart {
            get {
                return ResourceManager.GetString("labelNeedToRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人声选择: 的本地化字符串。
        /// </summary>
        internal static string labelPerson {
            get {
                return ResourceManager.GetString("labelPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音调: 的本地化字符串。
        /// </summary>
        internal static string labelPitch {
            get {
                return ResourceManager.GetString("labelPitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回放 API: 的本地化字符串。
        /// </summary>
        internal static string labelPlaybackApi {
            get {
                return ResourceManager.GetString("labelPlaybackApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出设备: 的本地化字符串。
        /// </summary>
        internal static string labelPlaybackDevice {
            get {
                return ResourceManager.GetString("labelPlaybackDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Secret Key: 的本地化字符串。
        /// </summary>
        internal static string labelSecretKey {
            get {
                return ResourceManager.GetString("labelSecretKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语速: 的本地化字符串。
        /// </summary>
        internal static string labelSpeed {
            get {
                return ResourceManager.GetString("labelSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引擎: 的本地化字符串。
        /// </summary>
        internal static string labelTTSEngine {
            get {
                return ResourceManager.GetString("labelTTSEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音量: 的本地化字符串。
        /// </summary>
        internal static string labelVolume {
            get {
                return ResourceManager.GetString("labelVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 立即清空缓存 的本地化字符串。
        /// </summary>
        internal static string linkLabelClearCache {
            get {
                return ResourceManager.GetString("linkLabelClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册 API 密钥 的本地化字符串。
        /// </summary>
        internal static string linkLabelOpenBaiduReg {
            get {
                return ResourceManager.GetString("linkLabelOpenBaiduReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开缓存文件夹 的本地化字符串。
        /// </summary>
        internal static string linkLabelOpenCacheDir {
            get {
                return ResourceManager.GetString("linkLabelOpenCacheDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设为推荐值 的本地化字符串。
        /// </summary>
        internal static string linkLabelSetRecommend {
            get {
                return ResourceManager.GetString("linkLabelSetRecommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确定要删除所有缓存的音频吗？ 的本地化字符串。
        /// </summary>
        internal static string messageAskClearCache {
            get {
                return ResourceManager.GetString("messageAskClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缓存已删除。 的本地化字符串。
        /// </summary>
        internal static string messageCacheCleared {
            get {
                return ResourceManager.GetString("messageCacheCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前已是最新版！ 的本地化字符串。
        /// </summary>
        internal static string messageLatest {
            get {
                return ResourceManager.GetString("messageLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现新的抢鲜版: {0}。 的本地化字符串。
        /// </summary>
        internal static string messageNewPrerelease {
            get {
                return ResourceManager.GetString("messageNewPrerelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现新的稳定版: {0}。 的本地化字符串。
        /// </summary>
        internal static string messageNewStable {
            get {
                return ResourceManager.GetString("messageNewStable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ACT 原生 TTS 的本地化字符串。
        /// </summary>
        internal static string radioButtonIntegrationAct {
            get {
                return ResourceManager.GetString("radioButtonIntegrationAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动检测 的本地化字符串。
        /// </summary>
        internal static string radioButtonIntegrationAuto {
            get {
                return ResourceManager.GetString("radioButtonIntegrationAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hojoring 语音合成 (TTSYukkuri) 的本地化字符串。
        /// </summary>
        internal static string radioButtonIntegrationYukkuri {
            get {
                return ResourceManager.GetString("radioButtonIntegrationYukkuri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用 ACT 的设置进行回放 的本地化字符串。
        /// </summary>
        internal static string radioButtonPlaybackACT {
            get {
                return ResourceManager.GetString("radioButtonPlaybackACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用内置回放 API 的本地化字符串。
        /// </summary>
        internal static string radioButtonPlaybackBuiltIn {
            get {
                return ResourceManager.GetString("radioButtonPlaybackBuiltIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用 TTSYukkuri 的设置进行回放 的本地化字符串。
        /// </summary>
        internal static string radioButtonPlaybackYukkuri {
            get {
                return ResourceManager.GetString("radioButtonPlaybackYukkuri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法加载当前的设置文件！ 的本地化字符串。
        /// </summary>
        internal static string settingsError {
            get {
                return ResourceManager.GetString("settingsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一次的设置文件备份也无法加载！ 的本地化字符串。
        /// </summary>
        internal static string settingsErrorBackup {
            get {
                return ResourceManager.GetString("settingsErrorBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你可以：
        ///1. 重置为默认设置，注意这将导致当前设置丢失！
        ///2. 直接忽略设置文件的错误并继续，这将不会更改任何现有设置，因此你可以手动检查你的设置文件并尝试恢复，但是本插件将无法正常工作！ 的本地化字符串。
        /// </summary>
        internal static string settingsErrorHintNoBackup {
            get {
                return ResourceManager.GetString("settingsErrorHintNoBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你可以：
        ///1.从上一次的设置备份中恢复，注意这将导致当前设置丢失！
        ///2.重置为默认设置，这也将导致当前设置丢失！
        ///3.直接忽略设置文件的错误并继续，这将不会更改任何现有设置，因此你可以手动检查你的设置文件并尝试恢复，但是本插件将无法正常工作！ 的本地化字符串。
        /// </summary>
        internal static string settingsErrorHintWithBackup {
            get {
                return ResourceManager.GetString("settingsErrorHintWithBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常规设置 的本地化字符串。
        /// </summary>
        internal static string tabPageGeneralSettings {
            get {
                return ResourceManager.GetString("tabPageGeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件日志 的本地化字符串。
        /// </summary>
        internal static string tabPageLog {
            get {
                return ResourceManager.GetString("tabPageLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 今天天气真不错。 的本地化字符串。
        /// </summary>
        internal static string textBoxPreview {
            get {
                return ResourceManager.GetString("textBoxPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 百度语音 的本地化字符串。
        /// </summary>
        internal static string ttsEngineBaidu {
            get {
                return ResourceManager.GetString("ttsEngineBaidu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查中... 的本地化字符串。
        /// </summary>
        internal static string updateChecking {
            get {
                return ResourceManager.GetString("updateChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        internal static string versionUnknown {
            get {
                return ResourceManager.GetString("versionUnknown", resourceCulture);
            }
        }
    }
}
