//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.FoxTTS.localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACT.FoxTTS.localization.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ACT TTS插件 的本地化字符串。
        /// </summary>
        internal static string actPanelTitle {
            get {
                return ResourceManager.GetString("actPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 男孩 的本地化字符串。
        /// </summary>
        internal static string azureRole_Boy {
            get {
                return ResourceManager.GetString("azureRole_Boy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        internal static string azureRole_Default {
            get {
                return ResourceManager.GetString("azureRole_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 女孩 的本地化字符串。
        /// </summary>
        internal static string azureRole_Girl {
            get {
                return ResourceManager.GetString("azureRole_Girl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旁白 的本地化字符串。
        /// </summary>
        internal static string azureRole_Narrator {
            get {
                return ResourceManager.GetString("azureRole_Narrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中年女性 的本地化字符串。
        /// </summary>
        internal static string azureRole_OlderAdultFemale {
            get {
                return ResourceManager.GetString("azureRole_OlderAdultFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中年男性 的本地化字符串。
        /// </summary>
        internal static string azureRole_OlderAdultMale {
            get {
                return ResourceManager.GetString("azureRole_OlderAdultMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 老年女性 的本地化字符串。
        /// </summary>
        internal static string azureRole_SeniorFemale {
            get {
                return ResourceManager.GetString("azureRole_SeniorFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 老年男性 的本地化字符串。
        /// </summary>
        internal static string azureRole_SeniorMale {
            get {
                return ResourceManager.GetString("azureRole_SeniorMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 青年女性 的本地化字符串。
        /// </summary>
        internal static string azureRole_YoungAdultFemale {
            get {
                return ResourceManager.GetString("azureRole_YoungAdultFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 青年男性 的本地化字符串。
        /// </summary>
        internal static string azureRole_YoungAdultMale {
            get {
                return ResourceManager.GetString("azureRole_YoungAdultMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 广告 的本地化字符串。
        /// </summary>
        internal static string azureStyle_advertisement_upbeat {
            get {
                return ResourceManager.GetString("azureStyle_advertisement-upbeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用兴奋和精力充沛的语气推广产品或服务。 的本地化字符串。
        /// </summary>
        internal static string azureStyle_advertisement_upbeat_Desc {
            get {
                return ResourceManager.GetString("azureStyle_advertisement-upbeat.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 亲切 的本地化字符串。
        /// </summary>
        internal static string azureStyle_affectionate {
            get {
                return ResourceManager.GetString("azureStyle_affectionate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以较高的音调和音量表达温暖而亲切的语气。 说话者处于吸引听众注意力的状态。 说话者的个性往往是讨喜的。 的本地化字符串。
        /// </summary>
        internal static string azureStyle_affectionate_Desc {
            get {
                return ResourceManager.GetString("azureStyle_affectionate.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生气 的本地化字符串。
        /// </summary>
        internal static string azureStyle_angry {
            get {
                return ResourceManager.GetString("azureStyle_angry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表达生气和厌恶的语气。 的本地化字符串。
        /// </summary>
        internal static string azureStyle_angry_Desc {
            get {
                return ResourceManager.GetString("azureStyle_angry.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 助理 的本地化字符串。
        /// </summary>
        internal static string azureStyle_assistant {
            get {
                return ResourceManager.GetString("azureStyle_assistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以热情而轻松的语气对数字助理讲话。 的本地化字符串。
        /// </summary>
        internal static string azureStyle_assistant_Desc {
            get {
                return ResourceManager.GetString("azureStyle_assistant.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平静 的本地化字符串。
        /// </summary>
        internal static string azureStyle_calm {
            get {
                return ResourceManager.GetString("azureStyle_calm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以沉着冷静的态度说话。 语气、音调和韵律与其他语音类型相比要统一得多。 的本地化字符串。
        /// </summary>
        internal static string azureStyle_calm_Desc {
            get {
                return ResourceManager.GetString("azureStyle_calm.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 聊天 的本地化字符串。
        /// </summary>
        internal static string azureStyle_chat {
            get {
                return ResourceManager.GetString("azureStyle_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表达轻松随意的语气。 的本地化字符串。
        /// </summary>
        internal static string azureStyle_chat_Desc {
            get {
                return ResourceManager.GetString("azureStyle_chat.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 愉悦 的本地化字符串。
        /// </summary>
        internal static string azureStyle_cheerful {
            get {
                return ResourceManager.GetString("azureStyle_cheerful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表达积极愉快的语气。 的本地化字符串。
        /// </summary>
        internal static string azureStyle_cheerful_Desc {
            get {
                return ResourceManager.GetString("azureStyle_cheerful.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客服 的本地化字符串。
        /// </summary>
        internal static string azureStyle_customerservice {
            get {
                return ResourceManager.GetString("azureStyle_customerservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以友好热情的语气为客户提供支持。 的本地化字符串。
        /// </summary>
        internal static string azureStyle_customerservice_Desc {
            get {
                return ResourceManager.GetString("azureStyle_customerservice.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 郁闷 的本地化字符串。
        /// </summary>
        internal static string azureStyle_depressed {
            get {
                return ResourceManager.GetString("azureStyle_depressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调低音调和音量来表达忧郁、沮丧的语气。 的本地化字符串。
        /// </summary>
        internal static string azureStyle_depressed_Desc {
            get {
                return ResourceManager.GetString("azureStyle_depressed.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不满 的本地化字符串。
        /// </summary>
        internal static string azureStyle_disgruntled {
            get {
                return ResourceManager.GetString("azureStyle_disgruntled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表达轻蔑和抱怨的语气。 这种情绪的语音表现出不悦和蔑视。 的本地化字符串。
        /// </summary>
        internal static string azureStyle_disgruntled_Desc {
            get {
                return ResourceManager.GetString("azureStyle_disgruntled.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尴尬 的本地化字符串。
        /// </summary>
        internal static string azureStyle_embarrassed {
            get {
                return ResourceManager.GetString("azureStyle_embarrassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在说话者感到不舒适时表达不确定、犹豫的语气。 的本地化字符串。
        /// </summary>
        internal static string azureStyle_embarrassed_Desc {
            get {
                return ResourceManager.GetString("azureStyle_embarrassed.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 善解人意 的本地化字符串。
        /// </summary>
        internal static string azureStyle_empathetic {
            get {
                return ResourceManager.GetString("azureStyle_empathetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表达关心和理解。 的本地化字符串。
        /// </summary>
        internal static string azureStyle_empathetic_Desc {
            get {
                return ResourceManager.GetString("azureStyle_empathetic.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 羡慕 的本地化字符串。
        /// </summary>
        internal static string azureStyle_envious {
            get {
                return ResourceManager.GetString("azureStyle_envious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当你渴望别人拥有的东西时，表达一种钦佩的语气。 的本地化字符串。
        /// </summary>
        internal static string azureStyle_envious_Desc {
            get {
                return ResourceManager.GetString("azureStyle_envious.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 激动 的本地化字符串。
        /// </summary>
        internal static string azureStyle_excited {
            get {
                return ResourceManager.GetString("azureStyle_excited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表达乐观和充满希望的语气。 似乎发生了一些美好的事情，说话人对此非常满意。 的本地化字符串。
        /// </summary>
        internal static string azureStyle_excited_Desc {
            get {
                return ResourceManager.GetString("azureStyle_excited.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 害怕 的本地化字符串。
        /// </summary>
        internal static string azureStyle_fearful {
            get {
                return ResourceManager.GetString("azureStyle_fearful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以较高的音调、较高的音量和较快的语速来表达恐惧、紧张的语气。 说话人处于紧张和不安的状态。 的本地化字符串。
        /// </summary>
        internal static string azureStyle_fearful_Desc {
            get {
                return ResourceManager.GetString("azureStyle_fearful.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 友好 的本地化字符串。
        /// </summary>
        internal static string azureStyle_friendly {
            get {
                return ResourceManager.GetString("azureStyle_friendly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表达一种愉快、怡人且温暖的语气。 听起来很真诚且满怀关切。 的本地化字符串。
        /// </summary>
        internal static string azureStyle_friendly_Desc {
            get {
                return ResourceManager.GetString("azureStyle_friendly.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 普通 的本地化字符串。
        /// </summary>
        internal static string azureStyle_general {
            get {
                return ResourceManager.GetString("azureStyle_general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 和蔼 的本地化字符串。
        /// </summary>
        internal static string azureStyle_gentle {
            get {
                return ResourceManager.GetString("azureStyle_gentle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以较低的音调和音量表达温和、礼貌和愉快的语气。 的本地化字符串。
        /// </summary>
        internal static string azureStyle_gentle_Desc {
            get {
                return ResourceManager.GetString("azureStyle_gentle.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 充满希望 的本地化字符串。
        /// </summary>
        internal static string azureStyle_hopeful {
            get {
                return ResourceManager.GetString("azureStyle_hopeful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表达一种温暖且渴望的语气。 听起来像是会有好事发生在说话人身上。 的本地化字符串。
        /// </summary>
        internal static string azureStyle_hopeful_Desc {
            get {
                return ResourceManager.GetString("azureStyle_hopeful.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抒情 的本地化字符串。
        /// </summary>
        internal static string azureStyle_lyrical {
            get {
                return ResourceManager.GetString("azureStyle_lyrical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以优美又带感伤的方式表达情感。 的本地化字符串。
        /// </summary>
        internal static string azureStyle_lyrical_Desc {
            get {
                return ResourceManager.GetString("azureStyle_lyrical.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旁白-专业 的本地化字符串。
        /// </summary>
        internal static string azureStyle_narration_professional {
            get {
                return ResourceManager.GetString("azureStyle_narration-professional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以专业、客观的语气朗读内容。 的本地化字符串。
        /// </summary>
        internal static string azureStyle_narration_professional_Desc {
            get {
                return ResourceManager.GetString("azureStyle_narration-professional.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旁白-轻松 的本地化字符串。
        /// </summary>
        internal static string azureStyle_narration_relaxed {
            get {
                return ResourceManager.GetString("azureStyle_narration-relaxed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 为内容阅读表达一种舒缓而悦耳的语气。 的本地化字符串。
        /// </summary>
        internal static string azureStyle_narration_relaxed_Desc {
            get {
                return ResourceManager.GetString("azureStyle_narration-relaxed.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 播音 的本地化字符串。
        /// </summary>
        internal static string azureStyle_newscast {
            get {
                return ResourceManager.GetString("azureStyle_newscast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新闻-非正式 的本地化字符串。
        /// </summary>
        internal static string azureStyle_newscast_casual {
            get {
                return ResourceManager.GetString("azureStyle_newscast-casual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以通用、随意的语气发布一般新闻。 的本地化字符串。
        /// </summary>
        internal static string azureStyle_newscast_casual_Desc {
            get {
                return ResourceManager.GetString("azureStyle_newscast-casual.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以正式专业的语气叙述新闻。 的本地化字符串。
        /// </summary>
        internal static string azureStyle_newscast_Desc {
            get {
                return ResourceManager.GetString("azureStyle_newscast.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新闻-正式 的本地化字符串。
        /// </summary>
        internal static string azureStyle_newscast_formal {
            get {
                return ResourceManager.GetString("azureStyle_newscast-formal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以正式、自信和权威的语气发布新闻。 的本地化字符串。
        /// </summary>
        internal static string azureStyle_newscast_formal_Desc {
            get {
                return ResourceManager.GetString("azureStyle_newscast-formal.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 诗歌朗诵 的本地化字符串。
        /// </summary>
        internal static string azureStyle_poetry_reading {
            get {
                return ResourceManager.GetString("azureStyle_poetry-reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在读诗时表达出带情感和节奏的语气。 的本地化字符串。
        /// </summary>
        internal static string azureStyle_poetry_reading_Desc {
            get {
                return ResourceManager.GetString("azureStyle_poetry-reading.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 悲伤 的本地化字符串。
        /// </summary>
        internal static string azureStyle_sad {
            get {
                return ResourceManager.GetString("azureStyle_sad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表达悲伤语气。 的本地化字符串。
        /// </summary>
        internal static string azureStyle_sad_Desc {
            get {
                return ResourceManager.GetString("azureStyle_sad.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 严肃 的本地化字符串。
        /// </summary>
        internal static string azureStyle_serious {
            get {
                return ResourceManager.GetString("azureStyle_serious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表达严肃和命令的语气。 说话者的声音通常比较僵硬，节奏也不那么轻松。 的本地化字符串。
        /// </summary>
        internal static string azureStyle_serious_Desc {
            get {
                return ResourceManager.GetString("azureStyle_serious.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 喊叫 的本地化字符串。
        /// </summary>
        internal static string azureStyle_shouting {
            get {
                return ResourceManager.GetString("azureStyle_shouting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 就像从遥远的地方说话或在外面说话，但能让自己清楚地听到。 的本地化字符串。
        /// </summary>
        internal static string azureStyle_shouting_Desc {
            get {
                return ResourceManager.GetString("azureStyle_shouting.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 体育解说 的本地化字符串。
        /// </summary>
        internal static string azureStyle_sports_commentary {
            get {
                return ResourceManager.GetString("azureStyle_sports-commentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用轻松有趣的语气播报体育赛事。 的本地化字符串。
        /// </summary>
        internal static string azureStyle_sports_commentary_Desc {
            get {
                return ResourceManager.GetString("azureStyle_sports-commentary.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 激情体育解说 的本地化字符串。
        /// </summary>
        internal static string azureStyle_sports_commentary_excited {
            get {
                return ResourceManager.GetString("azureStyle_sports-commentary-excited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用快速且充满活力的语气播报体育赛事精彩瞬间。 的本地化字符串。
        /// </summary>
        internal static string azureStyle_sports_commentary_excited_Desc {
            get {
                return ResourceManager.GetString("azureStyle_sports-commentary-excited.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恐惧 的本地化字符串。
        /// </summary>
        internal static string azureStyle_terrified {
            get {
                return ResourceManager.GetString("azureStyle_terrified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 说话非常柔和，发出的声音小且温柔。 的本地化字符串。
        /// </summary>
        internal static string azureStyle_terrified_Desc {
            get {
                return ResourceManager.GetString("azureStyle_terrified.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不友好 的本地化字符串。
        /// </summary>
        internal static string azureStyle_unfriendly {
            get {
                return ResourceManager.GetString("azureStyle_unfriendly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表达一种非常害怕的语气，语速快且声音颤抖。 听起来说话人处于不稳定的疯狂状态。 的本地化字符串。
        /// </summary>
        internal static string azureStyle_unfriendly_Desc {
            get {
                return ResourceManager.GetString("azureStyle_unfriendly.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 耳语 的本地化字符串。
        /// </summary>
        internal static string azureStyle_whispering {
            get {
                return ResourceManager.GetString("azureStyle_whispering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表达一种冷淡无情的语气。 的本地化字符串。
        /// </summary>
        internal static string azureStyle_whispering_Desc {
            get {
                return ResourceManager.GetString("azureStyle_whispering.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增规则 的本地化字符串。
        /// </summary>
        internal static string buttonAddRule {
            get {
                return ResourceManager.GetString("buttonAddRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查更新 的本地化字符串。
        /// </summary>
        internal static string buttonCheckUpdate {
            get {
                return ResourceManager.GetString("buttonCheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除规则 的本地化字符串。
        /// </summary>
        internal static string buttonDelRule {
            get {
                return ResourceManager.GetString("buttonDelRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开下载页面 的本地化字符串。
        /// </summary>
        internal static string buttonDownloadUpdate {
            get {
                return ResourceManager.GetString("buttonDownloadUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制规则 的本地化字符串。
        /// </summary>
        internal static string buttonDupRule {
            get {
                return ResourceManager.GetString("buttonDupRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 忽略错误（插件将无法正常工作） 的本地化字符串。
        /// </summary>
        internal static string buttonIgnore {
            get {
                return ResourceManager.GetString("buttonIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 忽略 的本地化字符串。
        /// </summary>
        internal static string buttonIgnoreVersion {
            get {
                return ResourceManager.GetString("buttonIgnoreVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下移 的本地化字符串。
        /// </summary>
        internal static string buttonMoveDown {
            get {
                return ResourceManager.GetString("buttonMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上移 的本地化字符串。
        /// </summary>
        internal static string buttonMoveUp {
            get {
                return ResourceManager.GetString("buttonMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 听听看! 的本地化字符串。
        /// </summary>
        internal static string buttonPreview {
            get {
                return ResourceManager.GetString("buttonPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置为默认设置 的本地化字符串。
        /// </summary>
        internal static string buttonResetToDefault {
            get {
                return ResourceManager.GetString("buttonResetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载上一次的设置 的本地化字符串。
        /// </summary>
        internal static string buttonRestoreFromBackup {
            get {
                return ResourceManager.GetString("buttonRestoreFromBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 稍后 的本地化字符串。
        /// </summary>
        internal static string buttonUpdateLater {
            get {
                return ResourceManager.GetString("buttonUpdateLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        internal static string buttonUpdateNow {
            get {
                return ResourceManager.GetString("buttonUpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 API Key: 的本地化字符串。
        /// </summary>
        internal static string checkBoxApiKey {
            get {
                return ResourceManager.GetString("checkBoxApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 勾选以显示 API Key。截图时请注意不要泄露！5秒后自动隐藏。 的本地化字符串。
        /// </summary>
        internal static string checkBoxApiKey_Tooltip {
            get {
                return ResourceManager.GetString("checkBoxApiKey.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 API Secret: 的本地化字符串。
        /// </summary>
        internal static string checkBoxApiSecret {
            get {
                return ResourceManager.GetString("checkBoxApiSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 勾选以显示 API Secret。截图时请注意不要泄露！5秒后自动隐藏。 的本地化字符串。
        /// </summary>
        internal static string checkBoxApiSecret_Tooltip {
            get {
                return ResourceManager.GetString("checkBoxApiSecret.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用ID: 的本地化字符串。
        /// </summary>
        internal static string checkBoxAppId {
            get {
                return ResourceManager.GetString("checkBoxAppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 勾选以显示应用ID。截图时请注意不要泄露！5秒后自动隐藏。 的本地化字符串。
        /// </summary>
        internal static string checkBoxAppId_Tooltip {
            get {
                return ResourceManager.GetString("checkBoxAppId.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 App Key: 的本地化字符串。
        /// </summary>
        internal static string checkBoxAppKey {
            get {
                return ResourceManager.GetString("checkBoxAppKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 勾选以显示 App Key。截图时请注意不要泄露！5秒后自动隐藏。 的本地化字符串。
        /// </summary>
        internal static string checkBoxAppKey_Tooltip {
            get {
                return ResourceManager.GetString("checkBoxAppKey.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用密钥: 的本地化字符串。
        /// </summary>
        internal static string checkBoxAppSecret {
            get {
                return ResourceManager.GetString("checkBoxAppSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 勾选以显示应用密钥。截图时请注意不要泄露！5秒后自动隐藏。 的本地化字符串。
        /// </summary>
        internal static string checkBoxAppSecret_Tooltip {
            get {
                return ResourceManager.GetString("checkBoxAppSecret.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动检查更新 的本地化字符串。
        /// </summary>
        internal static string checkBoxCheckUpdate {
            get {
                return ResourceManager.GetString("checkBoxCheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出时清空 TTS 缓存 的本地化字符串。
        /// </summary>
        internal static string checkBoxClearCacheExit {
            get {
                return ResourceManager.GetString("checkBoxClearCacheExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示调试日志 的本地化字符串。
        /// </summary>
        internal static string checkBoxDebugLogging {
            get {
                return ResourceManager.GetString("checkBoxDebugLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只提示稳定版更新 的本地化字符串。
        /// </summary>
        internal static string checkBoxNotifyStableOnly {
            get {
                return ResourceManager.GetString("checkBoxNotifyStableOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用规则 的本地化字符串。
        /// </summary>
        internal static string checkBoxRuleEnabled {
            get {
                return ResourceManager.GetString("checkBoxRuleEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Secret Key: 的本地化字符串。
        /// </summary>
        internal static string checkBoxSecretKey {
            get {
                return ResourceManager.GetString("checkBoxSecretKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 勾选以显示 Secret Key。截图时请注意不要泄露！5秒后自动隐藏。 的本地化字符串。
        /// </summary>
        internal static string checkBoxSecretKey_Tooltip {
            get {
                return ResourceManager.GetString("checkBoxSecretKey.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 播放下一句前立即终止当前播放的内容 的本地化字符串。
        /// </summary>
        internal static string checkBoxStopPrevious {
            get {
                return ResourceManager.GetString("checkBoxStopPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用 HTTPS 的本地化字符串。
        /// </summary>
        internal static string checkBoxUseHttps {
            get {
                return ResourceManager.GetString("checkBoxUseHttps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用正则 的本地化字符串。
        /// </summary>
        internal static string checkBoxUseRegex {
            get {
                return ResourceManager.GetString("checkBoxUseRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用 的本地化字符串。
        /// </summary>
        internal static string ColumnEnabled {
            get {
                return ResourceManager.GetString("ColumnEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 被替换的文本 的本地化字符串。
        /// </summary>
        internal static string ColumnFindPattern {
            get {
                return ResourceManager.GetString("ColumnFindPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 替换为 的本地化字符串。
        /// </summary>
        internal static string ColumnReplacement {
            get {
                return ResourceManager.GetString("ColumnReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用正则 的本地化字符串。
        /// </summary>
        internal static string ColumnUseRegex {
            get {
                return ResourceManager.GetString("ColumnUseRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认 的本地化字符串。
        /// </summary>
        internal static string comboBoxPitchDefault {
            get {
                return ResourceManager.GetString("comboBoxPitchDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高 的本地化字符串。
        /// </summary>
        internal static string comboBoxPitchHigh {
            get {
                return ResourceManager.GetString("comboBoxPitchHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 低 的本地化字符串。
        /// </summary>
        internal static string comboBoxPitchLow {
            get {
                return ResourceManager.GetString("comboBoxPitchLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中等 的本地化字符串。
        /// </summary>
        internal static string comboBoxPitchMedium {
            get {
                return ResourceManager.GetString("comboBoxPitchMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非常高 的本地化字符串。
        /// </summary>
        internal static string comboBoxPitchXHigh {
            get {
                return ResourceManager.GetString("comboBoxPitchXHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非常低 的本地化字符串。
        /// </summary>
        internal static string comboBoxPitchXLow {
            get {
                return ResourceManager.GetString("comboBoxPitchXLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认设备 的本地化字符串。
        /// </summary>
        internal static string deviceDefault {
            get {
                return ResourceManager.GetString("deviceDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件集成 的本地化字符串。
        /// </summary>
        internal static string groupBoxIntegration {
            get {
                return ResourceManager.GetString("groupBoxIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回放设置 的本地化字符串。
        /// </summary>
        internal static string groupBoxPlayback {
            get {
                return ResourceManager.GetString("groupBoxPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则设置 的本地化字符串。
        /// </summary>
        internal static string groupBoxPreprocessRules {
            get {
                return ResourceManager.GetString("groupBoxPreprocessRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 声音预览 的本地化字符串。
        /// </summary>
        internal static string groupBoxPreview {
            get {
                return ResourceManager.GetString("groupBoxPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TTS 引擎 的本地化字符串。
        /// </summary>
        internal static string groupBoxTTSEngine {
            get {
                return ResourceManager.GetString("groupBoxTTSEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引擎详情 的本地化字符串。
        /// </summary>
        internal static string groupBoxTTSEngineDetail {
            get {
                return ResourceManager.GetString("groupBoxTTSEngineDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件更新 的本地化字符串。
        /// </summary>
        internal static string groupBoxUpdate {
            get {
                return ResourceManager.GetString("groupBoxUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 免责声明：
        ///白嫖百度所造成的一切后果自负，与插件作者无关。
        ///该引擎随时可能失效，不保证任何可用性。 的本地化字符串。
        /// </summary>
        internal static string labelBaipiaoDisclaimer {
            get {
                return ResourceManager.GetString("labelBaipiaoDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前版本: 的本地化字符串。
        /// </summary>
        internal static string labelCurrentVersion {
            get {
                return ResourceManager.GetString("labelCurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 免责声明：
        ///白嫖微软所造成的一切后果自负，与插件作者无关。
        ///该引擎随时可能失效，不保证任何可用性。 的本地化字符串。
        /// </summary>
        internal static string labelEdgeDisclaimer {
            get {
                return ResourceManager.GetString("labelEdgeDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 被替换的文本： 的本地化字符串。
        /// </summary>
        internal static string labelFindPattern {
            get {
                return ResourceManager.GetString("labelFindPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 免责声明：
        ///白嫖谷歌所造成的一切后果自负，与插件作者无关。
        ///该引擎随时可能失效，不保证任何可用性。 的本地化字符串。
        /// </summary>
        internal static string labelGoogleDisclaimer {
            get {
                return ResourceManager.GetString("labelGoogleDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最新稳定版本: 的本地化字符串。
        /// </summary>
        internal static string labelLatestStableVersion {
            get {
                return ResourceManager.GetString("labelLatestStableVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最新版本: 的本地化字符串。
        /// </summary>
        internal static string labelLatestVersion {
            get {
                return ResourceManager.GetString("labelLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言: 的本地化字符串。
        /// </summary>
        internal static string labelMainLanguage {
            get {
                return ResourceManager.GetString("labelMainLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主音量: 的本地化字符串。
        /// </summary>
        internal static string labelMasterVolume {
            get {
                return ResourceManager.GetString("labelMasterVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 *需要重启ACT。 的本地化字符串。
        /// </summary>
        internal static string labelNeedToRestart {
            get {
                return ResourceManager.GetString("labelNeedToRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人声选择: 的本地化字符串。
        /// </summary>
        internal static string labelPerson {
            get {
                return ResourceManager.GetString("labelPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音调: 的本地化字符串。
        /// </summary>
        internal static string labelPitch {
            get {
                return ResourceManager.GetString("labelPitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回放 API: 的本地化字符串。
        /// </summary>
        internal static string labelPlaybackApi {
            get {
                return ResourceManager.GetString("labelPlaybackApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出设备: 的本地化字符串。
        /// </summary>
        internal static string labelPlaybackDevice {
            get {
                return ResourceManager.GetString("labelPlaybackDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正则表达式： 的本地化字符串。
        /// </summary>
        internal static string labelRegex {
            get {
                return ResourceManager.GetString("labelRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区域: 的本地化字符串。
        /// </summary>
        internal static string labelRegion {
            get {
                return ResourceManager.GetString("labelRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 替换为： 的本地化字符串。
        /// </summary>
        internal static string labelReplacement {
            get {
                return ResourceManager.GetString("labelReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色扮演: 的本地化字符串。
        /// </summary>
        internal static string labelRole {
            get {
                return ResourceManager.GetString("labelRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语速: 的本地化字符串。
        /// </summary>
        internal static string labelSpeed {
            get {
                return ResourceManager.GetString("labelSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 说话风格: 的本地化字符串。
        /// </summary>
        internal static string labelStyle {
            get {
                return ResourceManager.GetString("labelStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 风格强度: 的本地化字符串。
        /// </summary>
        internal static string labelStyleDegree {
            get {
                return ResourceManager.GetString("labelStyleDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引擎: 的本地化字符串。
        /// </summary>
        internal static string labelTTSEngine {
            get {
                return ResourceManager.GetString("labelTTSEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音量: 的本地化字符串。
        /// </summary>
        internal static string labelVolume {
            get {
                return ResourceManager.GetString("labelVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 立即清空缓存 的本地化字符串。
        /// </summary>
        internal static string linkLabelClearCache {
            get {
                return ResourceManager.GetString("linkLabelClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修复 Win10 TTS 人声列表 的本地化字符串。
        /// </summary>
        internal static string linkLabelCopyVoice {
            get {
                return ResourceManager.GetString("linkLabelCopyVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册 API 密钥 的本地化字符串。
        /// </summary>
        internal static string linkLabelOpenBaiduReg {
            get {
                return ResourceManager.GetString("linkLabelOpenBaiduReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开缓存文件夹 的本地化字符串。
        /// </summary>
        internal static string linkLabelOpenCacheDir {
            get {
                return ResourceManager.GetString("linkLabelOpenCacheDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册 API 密钥 的本地化字符串。
        /// </summary>
        internal static string linkLabelOpenXfyunReg {
            get {
                return ResourceManager.GetString("linkLabelOpenXfyunReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册应用密钥 的本地化字符串。
        /// </summary>
        internal static string linkLabelOpenYoudaoReg {
            get {
                return ResourceManager.GetString("linkLabelOpenYoudaoReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设为推荐值 的本地化字符串。
        /// </summary>
        internal static string linkLabelSetRecommend {
            get {
                return ResourceManager.GetString("linkLabelSetRecommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确定要删除所有缓存的音频吗？ 的本地化字符串。
        /// </summary>
        internal static string messageAskClearCache {
            get {
                return ResourceManager.GetString("messageAskClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确定要修复 Win10 人声列表吗？
        ///
        ///该操作涉及修改系统注册表，可能导致的一切后果自负！ 的本地化字符串。
        /// </summary>
        internal static string messageAskCopyVoice {
            get {
                return ResourceManager.GetString("messageAskCopyVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缓存已删除。 的本地化字符串。
        /// </summary>
        internal static string messageCacheCleared {
            get {
                return ResourceManager.GetString("messageCacheCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修复失败！详情请查看插件日志。 的本地化字符串。
        /// </summary>
        internal static string messageCopyVoiceFailed {
            get {
                return ResourceManager.GetString("messageCopyVoiceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修复成功！已更新 {0} 个人声：
        ///{1}
        ///
        ///请重启 ACT 以生效。 的本地化字符串。
        /// </summary>
        internal static string messageCopyVoiceSuccess {
            get {
                return ResourceManager.GetString("messageCopyVoiceSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前已是最新版！ 的本地化字符串。
        /// </summary>
        internal static string messageLatest {
            get {
                return ResourceManager.GetString("messageLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现新的抢鲜版: {0}。 的本地化字符串。
        /// </summary>
        internal static string messageNewPrerelease {
            get {
                return ResourceManager.GetString("messageNewPrerelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现新的稳定版: {0}。 的本地化字符串。
        /// </summary>
        internal static string messageNewStable {
            get {
                return ResourceManager.GetString("messageNewStable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你目前选择微软语音合成，该引擎需要自助申请 API Key 才可使用，普通用户建议在本插件的设置界面中选择其他引擎。
        ///
        ///请注意，你当前的设置会导致TTS没有声音！ 的本地化字符串。
        /// </summary>
        internal static string msgAzureApiKeyEmpty {
            get {
                return ResourceManager.GetString("msgAzureApiKeyEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你目前选择了百度TTS语音合成，该引擎需要自助申请 API Key 才可使用，普通用户建议在本插件的设置界面中选择其他引擎。
        ///
        ///请注意，你当前的设置会导致TTS没有声音！ 的本地化字符串。
        /// </summary>
        internal static string msgBaiduApiKeyEmpty {
            get {
                return ResourceManager.GetString("msgBaiduApiKeyEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本插件自带的免费百度语音 API Key 额度已经用完了，如需继续使用百度语音，请点击百度语音设置界面下方的 “注册 API 密钥” 按钮免费申请自己的 Key。
        ///
        ///已自动为你切换到了 CafeTTS。 的本地化字符串。
        /// </summary>
        internal static string msgBaiduFreeApiKeyExpired {
            get {
                return ResourceManager.GetString("msgBaiduFreeApiKeyExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误：身份认证失败，请确保在设置界面填入了正确的密钥与区域 的本地化字符串。
        /// </summary>
        internal static string msgErrorAzureAuthFail {
            get {
                return ResourceManager.GetString("msgErrorAzureAuthFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误：API 额度不足，你的 API Key 可用次数用完了，或者账户余额不足 的本地化字符串。
        /// </summary>
        internal static string msgErrorBaiduInsufficientApiQuota {
            get {
                return ResourceManager.GetString("msgErrorBaiduInsufficientApiQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误：你没有填 API/Secret Key！请确保在设置界面填入了正确的 API/Secret Key，否则会没有声音！ 的本地化字符串。
        /// </summary>
        internal static string msgErrorEmptyApiSecretKey {
            get {
                return ResourceManager.GetString("msgErrorEmptyApiSecretKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误：你没有填 Api Key/区域！请确保在设置界面填入了正确的 API Key 和区域，否则会没有声音！ 的本地化字符串。
        /// </summary>
        internal static string msgErrorEmptyKeyRegion {
            get {
                return ResourceManager.GetString("msgErrorEmptyKeyRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你的电脑无法使用 ACT 自带的声音播放 API，已自动切换到本插件内置的 WASAPI 播放方式。 的本地化字符串。
        /// </summary>
        internal static string msgErrorWMPUnavailable {
            get {
                return ResourceManager.GetString("msgErrorWMPUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误：身份认证失败，请确保在设置界面填入了正确的 API Secret/API Key 的本地化字符串。
        /// </summary>
        internal static string msgErrorXfyunAuthFail {
            get {
                return ResourceManager.GetString("msgErrorXfyunAuthFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误：API 额度不足，你的应用密钥可用次数用完了，或者账户余额不足，或者选择了未授权的发音人 的本地化字符串。
        /// </summary>
        internal static string msgErrorXfyunInsufficientApiQuota {
            get {
                return ResourceManager.GetString("msgErrorXfyunInsufficientApiQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误：身份认证失败，请确保在设置界面填入了正确的应用ID 的本地化字符串。
        /// </summary>
        internal static string msgErrorXfyunWrongAppId {
            get {
                return ResourceManager.GetString("msgErrorXfyunWrongAppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误：身份认证失败，请确保在设置界面填入了正确的应用ID/密钥 的本地化字符串。
        /// </summary>
        internal static string msgErrorYoudaoAuthFail {
            get {
                return ResourceManager.GetString("msgErrorYoudaoAuthFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误：API 额度不足，你的应用密钥可用次数用完了，或者账户余额不足 的本地化字符串。
        /// </summary>
        internal static string msgErrorYoudaoInsufficientApiQuota {
            get {
                return ResourceManager.GetString("msgErrorYoudaoInsufficientApiQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误：请求过于频繁，请稍后再试 的本地化字符串。
        /// </summary>
        internal static string msgErrorYoudaoTooFrequent {
            get {
                return ResourceManager.GetString("msgErrorYoudaoTooFrequent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误：文本过长 的本地化字符串。
        /// </summary>
        internal static string msgErrorYoudaoTooLong {
            get {
                return ResourceManager.GetString("msgErrorYoudaoTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 意料之外的错误代码 {0}，请参考有道智云语音合成服务API文档的错误代码列表，或联系开发者并提供插件日志。 的本地化字符串。
        /// </summary>
        internal static string msgErrorYoudaoUnexpected {
            get {
                return ResourceManager.GetString("msgErrorYoudaoUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你目前选择讯飞语音合成，该引擎需要自助申请 API Key 才可使用，普通用户建议在本插件的设置界面中选择其他引擎。
        ///
        ///请注意，你当前的设置会导致TTS没有声音！ 的本地化字符串。
        /// </summary>
        internal static string msgXfyunApiKeyEmpty {
            get {
                return ResourceManager.GetString("msgXfyunApiKeyEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你目前选择了有道TTS语音合成，该引擎需要自助申请应用密钥才可使用，普通用户建议在本插件的设置界面中选择其他引擎。
        ///
        ///请注意，你当前的设置会导致TTS没有声音！ 的本地化字符串。
        /// </summary>
        internal static string msgYoudaoAppKeyEmpty {
            get {
                return ResourceManager.GetString("msgYoudaoAppKeyEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [不推荐] ACT 原生 TTS 的本地化字符串。
        /// </summary>
        internal static string radioButtonIntegrationAct {
            get {
                return ResourceManager.GetString("radioButtonIntegrationAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动检测 的本地化字符串。
        /// </summary>
        internal static string radioButtonIntegrationAuto {
            get {
                return ResourceManager.GetString("radioButtonIntegrationAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [不推荐] Hojoring 语音合成 (TTSYukkuri) 的本地化字符串。
        /// </summary>
        internal static string radioButtonIntegrationYukkuri {
            get {
                return ResourceManager.GetString("radioButtonIntegrationYukkuri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [不推荐] 使用 ACT 的设置进行回放 的本地化字符串。
        /// </summary>
        internal static string radioButtonPlaybackACT {
            get {
                return ResourceManager.GetString("radioButtonPlaybackACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用内置回放 API 的本地化字符串。
        /// </summary>
        internal static string radioButtonPlaybackBuiltIn {
            get {
                return ResourceManager.GetString("radioButtonPlaybackBuiltIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [不推荐] 使用 TTSYukkuri 的设置进行回放 的本地化字符串。
        /// </summary>
        internal static string radioButtonPlaybackYukkuri {
            get {
                return ResourceManager.GetString("radioButtonPlaybackYukkuri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法加载当前的设置文件！ 的本地化字符串。
        /// </summary>
        internal static string settingsError {
            get {
                return ResourceManager.GetString("settingsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一次的设置文件备份也无法加载！ 的本地化字符串。
        /// </summary>
        internal static string settingsErrorBackup {
            get {
                return ResourceManager.GetString("settingsErrorBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你可以：
        ///1. 重置为默认设置，注意这将导致当前设置丢失！
        ///2. 直接忽略设置文件的错误并继续，这将不会更改任何现有设置，因此你可以手动检查你的设置文件并尝试恢复，但是本插件将无法正常工作！ 的本地化字符串。
        /// </summary>
        internal static string settingsErrorHintNoBackup {
            get {
                return ResourceManager.GetString("settingsErrorHintNoBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你可以：
        ///1.从上一次的设置备份中恢复，注意这将导致当前设置丢失！
        ///2.重置为默认设置，这也将导致当前设置丢失！
        ///3.直接忽略设置文件的错误并继续，这将不会更改任何现有设置，因此你可以手动检查你的设置文件并尝试恢复，但是本插件将无法正常工作！ 的本地化字符串。
        /// </summary>
        internal static string settingsErrorHintWithBackup {
            get {
                return ResourceManager.GetString("settingsErrorHintWithBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常规设置 的本地化字符串。
        /// </summary>
        internal static string tabPageGeneralSettings {
            get {
                return ResourceManager.GetString("tabPageGeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件日志 的本地化字符串。
        /// </summary>
        internal static string tabPageLog {
            get {
                return ResourceManager.GetString("tabPageLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本处理 的本地化字符串。
        /// </summary>
        internal static string tabPageTextProcessor {
            get {
                return ResourceManager.GetString("tabPageTextProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 今天天气真不错。 的本地化字符串。
        /// </summary>
        internal static string textBoxPreview {
            get {
                return ResourceManager.GetString("textBoxPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 微软语音 的本地化字符串。
        /// </summary>
        internal static string ttsEngineAzure {
            get {
                return ResourceManager.GetString("ttsEngineAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 百度语音 的本地化字符串。
        /// </summary>
        internal static string ttsEngineBaidu {
            get {
                return ResourceManager.GetString("ttsEngineBaidu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 百度语音（白嫖） 的本地化字符串。
        /// </summary>
        internal static string ttsEngineBaipiao {
            get {
                return ResourceManager.GetString("ttsEngineBaipiao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 肥肥咖啡（FFCafe）TTS 的本地化字符串。
        /// </summary>
        internal static string ttsEngineCafe {
            get {
                return ResourceManager.GetString("ttsEngineCafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 肥肥咖啡（FFCafe）TTS Pro 的本地化字符串。
        /// </summary>
        internal static string ttsEngineCafePro {
            get {
                return ResourceManager.GetString("ttsEngineCafePro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 微软语音（白嫖） 的本地化字符串。
        /// </summary>
        internal static string ttsEngineEdge {
            get {
                return ResourceManager.GetString("ttsEngineEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 谷歌语音（白嫖） 的本地化字符串。
        /// </summary>
        internal static string ttsEngineGoogleUnofficial {
            get {
                return ResourceManager.GetString("ttsEngineGoogleUnofficial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统自带 TTS 的本地化字符串。
        /// </summary>
        internal static string ttsEngineSAPI5 {
            get {
                return ResourceManager.GetString("ttsEngineSAPI5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 讯飞语音 的本地化字符串。
        /// </summary>
        internal static string ttsEngineXfyun {
            get {
                return ResourceManager.GetString("ttsEngineXfyun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有道智云 TTS 的本地化字符串。
        /// </summary>
        internal static string ttsEngineYoudao {
            get {
                return ResourceManager.GetString("ttsEngineYoudao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查中... 的本地化字符串。
        /// </summary>
        internal static string updateChecking {
            get {
                return ResourceManager.GetString("updateChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        internal static string versionUnknown {
            get {
                return ResourceManager.GetString("versionUnknown", resourceCulture);
            }
        }
    }
}
